volumes:
  subspace-node-data: {}

services:
  subspace-node:
    image: ghcr.io/autonomys/node:${NODE_DOCKER_TAG}
    volumes:
      - subspace-node-data:/var/subspace:rw
    ports:
      - '30333:30333'
      - '30433:30433'
      - '9944:9944'
    restart: unless-stopped
    command:
      [
        'run',
        '--chain',
        '${NETWORK_ID}',
        '--base-path',
        '/var/subspace',
        '--listen-on',
        '/ip4/0.0.0.0/tcp/30333',
        '--dsn-listen-on',
        '/ip4/0.0.0.0/tcp/30433',
        '--rpc-cors',
        'all',
        '--rpc-methods',
        'unsafe',
        '--rpc-listen-on',
        '0.0.0.0:9944',
        '--rpc-max-subscriptions-per-connection',
        '1000',
        '--rpc-max-connections',
        '20000',
        '--farmer',
        '--name',
        'object-mapping-node',
        '--sync',
        'full',
        '--create-object-mappings',
        '${BLOCK_NUMBER_TO_START_FROM}',
      ]
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 60
    stop_grace_period: 30s
  object-mapping-app:
    image: node:20
    container_name: object-mapping-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - RPC_URL=ws://subspace-node:9944
    entrypoint: ['bash', './start-server.sh']
    depends_on:
      subspace-node:
        condition: service_healthy
    restart: unless-stopped
