volumes:
  node-data: {}

services:
  node:
    image: ghcr.io/autonomys/node:${NODE_DOCKER_TAG}
    volumes:
      - node-data:/var/subspace:rw
    ports:
      - '30333:30333'
      - '30433:30433'
      - '9944:9944'
    restart: unless-stopped
    command:
      [
        'run',
        '--chain',
        '${NETWORK_ID}',
        '--base-path',
        '/var/subspace',
        '--pot-external-entropy',
        '00000000000000000000d695f8a14ff24a8dfb68245cec4a4b6787de86e232fe',
        '--listen-on',
        '/ip4/0.0.0.0/tcp/30333',
        '--dsn-listen-on',
        '/ip4/0.0.0.0/tcp/30433',
        '--rpc-cors',
        'all',
        '--rpc-methods',
        'unsafe',
        '--rpc-listen-on',
        '0.0.0.0:9944',
        '--rpc-max-subscriptions-per-connection',
        '1000',
        '--rpc-max-connections',
        '20000',
        '--farmer',
        '--name',
        'object-mapping-node',
        '--sync',
        'full',
        '--create-object-mappings',
        '${BLOCK_NUMBER_TO_START_FROM}',
      ]
    stop_grace_period: 30s
    healthcheck:
      timeout: 5s
      interval: 30s
      retries: 60
