services:
  dag-indexer:
    extends:
      file: ./docker-compose.yml
      service: dag-indexer
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
