services:
  dag-indexer:
    image: ghcr.io/autonomys/subql-node-substrate:latest
    ports:
      - '127.0.0.1:30001:3000'
    volumes:
      - ../../services/dag-indexer:/app
    working_dir: /app
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10
    environment:
      # Database configuration
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      # Blockchain configuration (required)
      CHAIN_ID: ${CHAIN_ID}
      RPC_ENDPOINTS: ${RPC_ENDPOINTS}
      START_BLOCK: ${START_BLOCK:-0}
    restart: unless-stopped
    command: >
      --db-schema=dag-indexer
      --workers=1
      --unsafe
      --batch-size=125
      --scale-batch-size
      --unfinalized-blocks=true
      --disable-historical=false
      --finalized-depth=100
