volumes:
  subspace-node-data: {}
  file-retriever-data: {}

services:
  subspace-node:
    extends:
      file: ./docker-compose.yml
      service: subspace-node
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  object-mapping-app:
    extends:
      file: ./docker-compose.yml
      service: object-mapping-app
    container_name: object-mapping-app
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  agent:
    extends:
      file: ./docker-compose.yml
      service: agent
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
