volumes:
  subspace-node-data: {}
  file-retriever-data: {}

services:
  subspace-node:
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  object-mapping-app:
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  agent:
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
