volumes:
  subspace-node-data: {}
  file-retriever-data: {}

services:
  subspace-rpc-gateway:
    extends:
      file: docker-compose.yml
      service: subspace-rpc-gateway
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  file-retriever:
    extends:
      file: docker-compose.yml
      service: file-retriever
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
  agent:
    extends:
      file: docker-compose.yml
      service: agent
    logging:
      driver: loki
      options:
        loki-url: 'https://logging.subspace.network/loki/api/v1/push'
