volumes:
  subspace-node-data: {}
  file-retriever-data: {}

services:
  subspace-rpc-gateway:
    image: ${GATEWAY_DOCKER_TAG}
    depends_on:
      subspace-node:
        condition: service_healthy
    ports:
      - '9955:9955'
      - '30334:30333'
      - '30434:30433'
    restart: unless-stopped
    stop_grace_period: 30s
    command: rpc --node-rpc-url ws://subspace-node:9944/ws --rpc-listen-on 0.0.0.0:9955 --allow-private-ips --out-connections ${OUT_CONNECTIONS} --pending-out-connections ${PENDING_OUT_CONNECTIONS}
    environment:
      - RUST_LOG=${RUST_LOG_GATEWAY:-info}
  file-retriever:
    image: ${FILE_RETRIEVER_DOCKER_TAG}
    container_name: file-retriever
    volumes:
      - file-retriever-data:/app/services/file-retriever/.cache
    ports:
      - '8090:8090'
    environment:
      - NODE_ENV=production
      - SUBSPACE_GATEWAY_URLS=http://subspace-rpc-gateway:9955
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MAX_SIMULTANEOUS_FETCHES=${MAX_SIMULTANEOUS_FETCHES}
      - CACHE_DIR=${CACHE_DIR}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE}
      - CACHE_TTL=${CACHE_TTL}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_SECRET=${API_SECRET}
      - VICTORIA_ACTIVE=${VICTORIA_ACTIVE}
      - VICTORIA_ENDPOINT=${VICTORIA_ENDPOINT}
      - METRIC_ENVIRONMENT_TAG=${METRIC_ENVIRONMENT_TAG}
      - VICTORIA_USERNAME=${VICTORIA_USERNAME}
      - VICTORIA_PASSWORD=${VICTORIA_PASSWORD}
      - OBJECT_MAPPING_INDEXER_URL=http://object-mapping-app:3000/ws
    depends_on:
      subspace-node:
        condition: service_healthy
    restart: unless-stopped
  file-retriever-2:
    image: ${FILE_RETRIEVER_DOCKER_TAG}
    container_name: file-retriever-2
    volumes:
      - file-retriever-data:/app/services/file-retriever/.cache
    ports:
      - '8090:8090'
    environment:
      - NODE_ENV=production
      - SUBSPACE_GATEWAY_URLS=http://subspace-rpc-gateway:9955
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MAX_SIMULTANEOUS_FETCHES=${MAX_SIMULTANEOUS_FETCHES}
      - CACHE_DIR=${CACHE_DIR}
      - CACHE_MAX_SIZE=${CACHE_MAX_SIZE}
      - CACHE_TTL=${CACHE_TTL}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_SECRET=${API_SECRET}
      - VICTORIA_ACTIVE=${VICTORIA_ACTIVE}
      - VICTORIA_ENDPOINT=${VICTORIA_ENDPOINT}
      - METRIC_ENVIRONMENT_TAG=${METRIC_ENVIRONMENT_TAG}
      - VICTORIA_USERNAME=${VICTORIA_USERNAME}
      - VICTORIA_PASSWORD=${VICTORIA_PASSWORD}
      - OBJECT_MAPPING_INDEXER_URL=http://object-mapping-app:3000/ws
    depends_on:
      subspace-node:
        condition: service_healthy
    restart: unless-stopped
  agent:
    profiles:
      - production
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: bridge
    pid: host
    privileged: true
    volumes:
      - '/:/host:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      NRIA_LICENSE_KEY: ${NR_API_KEY}
      NRIA_DISPLAY_NAME: ${NR_AGENT_IDENTIFIER}
    restart: unless-stopped
