name: Services

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  backend-build-check:
    name: Services Build, Test and Lint Check
    runs-on: ubuntu-latest

    # Cache dependencies to speed up the workflow
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        run: corepack use yarn@4.2.2

      - name: Build all services
        run: make -B all

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
